development:
  adapter: postgresql
  database: ecmash_development
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: ecmash_test
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  database: ecmash_production
  host: localhost
  encoding: utf8
